steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/milky-way/sveltekit-cd:1.0.0'
      - '.'
  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/milky-way/sveltekit-cd:1.0.0'
  # Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sveltekit-cd'
      - '--image=asia-southeast2-docker.pkg.dev/$PROJECT_ID/milky-way/sveltekit-cd:1.0.0'
      - '--platform=managed'
      - '--region=asia-southeast2'